### ISSUE TITLE
afk page 

### ISSUE THREAD

**Issue by DEAM0** [FyreSoftware/Fyreactyl#25]
An error has occured and you have been disconnected from the AFK page.

To resolve this error, you must reload the page.

Error: An unexpected error has occured that resulted in the AFK page crashing.

Automatically attempting to reconnect in 2...

**Comment by tovade** [comment]
This is a known issue, and won't be fixed cause i have tried with always resulting into it not working. I don't know why it doesn't want to work. So this won't be fixed in v1. Wait for v2 if you want it fixed.
