### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by crafter-hub** [FyreSoftware/Fyreactyl#29]
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

How do I fix?

**Comment by GeorgeV220** [comment]
Hello, Please send the whole log

**Comment by crafter-hub** [comment]
> Hello, Please send the whole log

That is the whole log

**Comment by GeorgeV220** [comment]
That's sound like axios error but I don't remember if the project is using axios. Please check your URL if it is correct and let me know

**Comment by tovade** [comment]
its a database error, and yes this uses axios mainly for requests to the pterodactyl panel
