### ISSUE TITLE
Bug in the renew button

### ISSUE THREAD

**Issue by Jeanlx** [FyreSoftware/Fyreactyl#30]
When you have more than 1 server on the board and you want to renew any server on the list, it cannot be renewed because if you try, the first one on the list will be renewed but not the other servers.

I want to renew the second server.. 
![image](https://user-images.githubusercontent.com/86314622/204110496-95cc1ddd-42fc-4e8c-bb03-965147ba65db.png)

I give it to renew and nothing happens.. I hit renew and nothing happens... but the first server on the list does renew

**Comment by tovade** [comment]
fixed in [this commit](https://github.com/FyreSoftware/Fyreactyl/commit/987a69d8fdc883c91867e999bcedc594d538331a)
